//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        public Client()
        {
            this.Message = new HashSet<Message>();
            this.Reservation = new HashSet<Reservation>();
        }
    
        public int userId { get; set; }
        public string firstName { get; set; }
        public string pLastName { get; set; }
        public string mLastName { get; set; }
        public string telephone { get; set; }
        public int clientId { get; set; }
    
        public virtual Account Account { get; set; }
        public virtual ICollection<Message> Message { get; set; }
        public virtual ICollection<Reservation> Reservation { get; set; }
    }
}
