//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34011
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationUI.ServiceReference1 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="CompositeType", Namespace="http://schemas.datacontract.org/2004/07/ResevationService")]
    [System.SerializableAttribute()]
    public partial class CompositeType : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool BoolValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StringValueField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool BoolValue {
            get {
                return this.BoolValueField;
            }
            set {
                if ((this.BoolValueField.Equals(value) != true)) {
                    this.BoolValueField = value;
                    this.RaisePropertyChanged("BoolValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StringValue {
            get {
                return this.StringValueField;
            }
            set {
                if ((object.ReferenceEquals(this.StringValueField, value) != true)) {
                    this.StringValueField = value;
                    this.RaisePropertyChanged("StringValue");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceReference1.IService1")]
    public interface IService1 {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        string GetData(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetData", ReplyAction="http://tempuri.org/IService1/GetDataResponse")]
        System.Threading.Tasks.Task<string> GetDataAsync(int value);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        ReservationUI.ServiceReference1.CompositeType GetDataUsingDataContract(ReservationUI.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDataUsingDataContract", ReplyAction="http://tempuri.org/IService1/GetDataUsingDataContractResponse")]
        System.Threading.Tasks.Task<ReservationUI.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ReservationUI.ServiceReference1.CompositeType composite);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllBusiness", ReplyAction="http://tempuri.org/IService1/GetAllBusinessResponse")]
        System.Data.DataSet GetAllBusiness(int typeId, int directionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAllBusiness", ReplyAction="http://tempuri.org/IService1/GetAllBusinessResponse")]
        System.Threading.Tasks.Task<System.Data.DataSet> GetAllBusinessAsync(int typeId, int directionId);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAccount", ReplyAction="http://tempuri.org/IService1/GetAccountResponse")]
        ReservationModel.Account GetAccount(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetAccount", ReplyAction="http://tempuri.org/IService1/GetAccountResponse")]
        System.Threading.Tasks.Task<ReservationModel.Account> GetAccountAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetReservation", ReplyAction="http://tempuri.org/IService1/GetReservationResponse")]
        ReservationModel.Reservation GetReservation(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetReservation", ReplyAction="http://tempuri.org/IService1/GetReservationResponse")]
        System.Threading.Tasks.Task<ReservationModel.Reservation> GetReservationAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMessage", ReplyAction="http://tempuri.org/IService1/GetMessageResponse")]
        ReservationModel.Message GetMessage(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetMessage", ReplyAction="http://tempuri.org/IService1/GetMessageResponse")]
        System.Threading.Tasks.Task<ReservationModel.Message> GetMessageAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetClient", ReplyAction="http://tempuri.org/IService1/GetClientResponse")]
        ReservationModel.Client GetClient(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetClient", ReplyAction="http://tempuri.org/IService1/GetClientResponse")]
        System.Threading.Tasks.Task<ReservationModel.Client> GetClientAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStyle", ReplyAction="http://tempuri.org/IService1/GetStyleResponse")]
        ReservationModel.Style GetStyle(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetStyle", ReplyAction="http://tempuri.org/IService1/GetStyleResponse")]
        System.Threading.Tasks.Task<ReservationModel.Style> GetStyleAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDirection", ReplyAction="http://tempuri.org/IService1/GetDirectionResponse")]
        ReservationModel.Direction GetDirection(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetDirection", ReplyAction="http://tempuri.org/IService1/GetDirectionResponse")]
        System.Threading.Tasks.Task<ReservationModel.Direction> GetDirectionAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBusiness", ReplyAction="http://tempuri.org/IService1/GetBusinessResponse")]
        ReservationModel.Business GetBusiness(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/GetBusiness", ReplyAction="http://tempuri.org/IService1/GetBusinessResponse")]
        System.Threading.Tasks.Task<ReservationModel.Business> GetBusinessAsync(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateAccount", ReplyAction="http://tempuri.org/IService1/CreateAccountResponse")]
        bool CreateAccount(ReservationModel.Account account);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IService1/CreateAccount", ReplyAction="http://tempuri.org/IService1/CreateAccountResponse")]
        System.Threading.Tasks.Task<bool> CreateAccountAsync(ReservationModel.Account account);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IService1Channel : ReservationUI.ServiceReference1.IService1, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class Service1Client : System.ServiceModel.ClientBase<ReservationUI.ServiceReference1.IService1>, ReservationUI.ServiceReference1.IService1 {
        
        public Service1Client() {
        }
        
        public Service1Client(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public Service1Client(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public Service1Client(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string GetData(int value) {
            return base.Channel.GetData(value);
        }
        
        public System.Threading.Tasks.Task<string> GetDataAsync(int value) {
            return base.Channel.GetDataAsync(value);
        }
        
        public ReservationUI.ServiceReference1.CompositeType GetDataUsingDataContract(ReservationUI.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContract(composite);
        }
        
        public System.Threading.Tasks.Task<ReservationUI.ServiceReference1.CompositeType> GetDataUsingDataContractAsync(ReservationUI.ServiceReference1.CompositeType composite) {
            return base.Channel.GetDataUsingDataContractAsync(composite);
        }
        
        public System.Data.DataSet GetAllBusiness(int typeId, int directionId) {
            return base.Channel.GetAllBusiness(typeId, directionId);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataSet> GetAllBusinessAsync(int typeId, int directionId) {
            return base.Channel.GetAllBusinessAsync(typeId, directionId);
        }
        
        public ReservationModel.Account GetAccount(int id) {
            return base.Channel.GetAccount(id);
        }
        
        public System.Threading.Tasks.Task<ReservationModel.Account> GetAccountAsync(int id) {
            return base.Channel.GetAccountAsync(id);
        }
        
        public ReservationModel.Reservation GetReservation(int id) {
            return base.Channel.GetReservation(id);
        }
        
        public System.Threading.Tasks.Task<ReservationModel.Reservation> GetReservationAsync(int id) {
            return base.Channel.GetReservationAsync(id);
        }
        
        public ReservationModel.Message GetMessage(int id) {
            return base.Channel.GetMessage(id);
        }
        
        public System.Threading.Tasks.Task<ReservationModel.Message> GetMessageAsync(int id) {
            return base.Channel.GetMessageAsync(id);
        }
        
        public ReservationModel.Client GetClient(int id) {
            return base.Channel.GetClient(id);
        }
        
        public System.Threading.Tasks.Task<ReservationModel.Client> GetClientAsync(int id) {
            return base.Channel.GetClientAsync(id);
        }
        
        public ReservationModel.Style GetStyle(int id) {
            return base.Channel.GetStyle(id);
        }
        
        public System.Threading.Tasks.Task<ReservationModel.Style> GetStyleAsync(int id) {
            return base.Channel.GetStyleAsync(id);
        }
        
        public ReservationModel.Direction GetDirection(int id) {
            return base.Channel.GetDirection(id);
        }
        
        public System.Threading.Tasks.Task<ReservationModel.Direction> GetDirectionAsync(int id) {
            return base.Channel.GetDirectionAsync(id);
        }
        
        public ReservationModel.Business GetBusiness(int id) {
            return base.Channel.GetBusiness(id);
        }
        
        public System.Threading.Tasks.Task<ReservationModel.Business> GetBusinessAsync(int id) {
            return base.Channel.GetBusinessAsync(id);
        }
        
        public bool CreateAccount(ReservationModel.Account account) {
            return base.Channel.CreateAccount(account);
        }
        
        public System.Threading.Tasks.Task<bool> CreateAccountAsync(ReservationModel.Account account) {
            return base.Channel.CreateAccountAsync(account);
        }
    }
}
