//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Account
    {
        public string password { get; set; }
        public string userName { get; set; }
        public int userTypeId { get; set; }
        public int userId { get; set; }
        public Nullable<int> directionId { get; set; }
    
        public virtual Direction Direction { get; set; }
        public virtual Business Business { get; set; }
        public virtual Client Client { get; set; }
    }
}
