//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Message
    {
        public int messageId { get; set; }
        public int bUserId { get; set; }
        public string messageText { get; set; }
        public System.TimeSpan mTime { get; set; }
        public Nullable<int> cUserId { get; set; }
        public Nullable<System.DateTime> mDay { get; set; }
    
        public virtual Business Business { get; set; }
        public virtual Client Client { get; set; }
    }
}
