//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReservationModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ReservationAppEntities1 : DbContext
    {
        public ReservationAppEntities1()
            : base("name=ReservationAppEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Account> Account { get; set; }
        public DbSet<Business> Business { get; set; }
        public DbSet<Client> Client { get; set; }
        public DbSet<Direction> Direction { get; set; }
        public DbSet<Message> Message { get; set; }
        public DbSet<Reservation> Reservation { get; set; }
        public DbSet<Style> Style { get; set; }
        public DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
